name: publish

on:
  push:
    tags:
      - v*

jobs:
  build-publish-docker-images:
    runs-on: ubuntu-latest

    steps:
    - name: Branch name
      id: branch_name
      run: |
        echo ::set-output name=SOURCE_TAG::${GITHUB_REF#refs/tags/}

    - uses: actions/checkout@v2
    - run: |
        git fetch --tags

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build Docker images
      env:
        SOURCE_TAG: ${{ steps.branch_name.outputs.SOURCE_TAG }}
      run: |
        .ci/scripts/run.sh
       